<?php

namespace FondOfSpryker\Shared\ProductPageSearchAttributeExpander;

interface ProductPageSearchAttributeExpanderConstants
{
    public const SORTABLE_INTEGER_ATTRIBUTES = 'FOND_OF_SPRYKER:PRODUCT_PAGE_SEARCH_ATTRIBUTE_EXPANDER:SORTABLE_INTEGER_ATTRIBUTES';
    public const DEFAULT_SORTABLE_INTEGER_ATTRIBUTES = [];

    public const SORTABLE_STRING_ATTRIBUTES = 'FOND_OF_SPRYKER:PRODUCT_PAGE_SEARCH_ATTRIBUTE_EXPANDER:SORTABLE_STRING_ATTRIBUTES';
    public const DEFAULT_SORTABLE_STRING_ATTRIBUTES = [];
}
